interface/urls.py
from django.urls import path
from . import views
from .views import deploying_page

app_name = "interface"

urlpatterns = [
    path("accounts/login/", views.login_view, name="login"),
    path("accounts/logout/", views.logout_view, name="logout"),
    path("accounts/signup/", views.signup_view, name="signup"),
    path("lead_generator/", views.lead_generator_view, name="lead_generator"),
    path("deploying/", deploying_page, name="deploying"),
]

lead_generation_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("interface.urls", namespace="interface")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

interface/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

interface/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class LeadGeneratorForm(forms.Form):
    keywords = forms.CharField(
        label="Keywords",
        widget=forms.TextInput(
            attrs={"placeholder": "Hotel, Gym", "autocomplete": "off"}
        ),
    )
    location = forms.CharField(
        label="Location",
        widget=forms.TextInput(
            attrs={"placeholder": "Lviv, Rivne", "autocomplete": "off"}
        ),
    )
    leads_num = forms.ChoiceField(
        label="Number of Leads", choices=[(i, str(i)) for i in range(1, 201)]
    )


class SignupForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ("email", "username", "password1", "password2")

interface/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from .forms import LeadGeneratorForm, SignupForm


def login_view(request):
    form = AuthenticationForm()

    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("interface:lead_generator")
            else:
                print("Invalid credentials")

    return render(request, "registration/login.html", {"form": form})


def logout_view(request):
    logout(request)
    return render(request, "registration/logged_out.html")


def signup_view(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("interface:lead_generator")
    else:
        form = SignupForm()
    return render(request, "registration/signup.html", {"form": form})


@login_required
def lead_generator_view(request):
    form = LeadGeneratorForm()

    if request.method == "POST":
        form = LeadGeneratorForm(request.POST)
        if form.is_valid():
            keywords = form.cleaned_data["keywords"]
            location = form.cleaned_data["location"]
            leads_num = form.cleaned_data["leads_num"]

            return redirect("interface:lead_generator")

    return render(request, "interface/lead_generator.html", {"form": form})


def deploying_page(request):
    return render(request, "interface/deploying_page.html")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" itemscope itemtype="http://schema.org/WebPage">

<head>

<meta charset="utf-8" />

<title>
  Interface
</title>
<!--     Fonts and icons     -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />

<!-- CSS Files -->
<link id="pagestyle" href="{% static 'css/soft-design-system.css' %}" rel="stylesheet" />
</head>
<style>
  body {
    padding-top:5px;
  }
</style>
<body {% block body %}{% endblock body %} >

  {% block header %}
  <div style=margin-bottom:100px;">

    {% include 'includes/sidebar.html' %}
  </div>

  {% endblock header %}

  <div class="mx-lg-5 mx-md-3 mx-sm-1 px-lg-5 px-md-3 px-sm-0">

    {% block content %}{% endblock content %}
  </div>


</body>
</html>

templates/includes/sidebar.html
{% load static %}
<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav
        class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid px-0">
          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse"
            data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon mt-2"></span>
            <span class="navbar-toggler-bar bar1"></span>
            <span class="navbar-toggler-bar bar2"></span>
            <span class="navbar-toggler-bar bar3"></span>
          </button>
          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
            <a class="navbar-brand font-weight-bolder ms-sm-7"
              href="{% url 'interface:lead_generator' %}" rel="tooltip"
              title="Click to see Lead Generator" data-placement="bottom">
              Lead Generator
            </a>

            {% if request.user.is_authenticated %}
              <a class="nav-item ms-lg-auto font-weight-bold fa fa-sign-out me-5"
              href="{% url 'interface:logout' %}" rel="tooltip" data-placement="bottom">
              Logout
              </a>
            {% else %}
              <a class="nav-item ms-lg-auto font-weight-bold fa fa-sign-out me-5"
              href="{% url 'interface:signup' %}" rel="tooltip" data-placement="bottom">
              Sign Up
              </a>
              <a class="nav-item ms-lg-auto font-weight-bold fa fa-sign-out me-5"
              href="{% url 'interface:login' %}" rel="tooltip" data-placement="bottom">
              Login
              </a>
            {% endif %}

              <a href="https://github.com/oksanaaam/lead_generation_service" target="_blank"
                class="btn btn-sm  bg-gradient-primary  btn-round mb-0 me-1 mt-2 mt-md-0">Git hub</a>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
    </div>
  </div>
</div>

templates/interface/deploying_page.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<section>
  <div class="page-header min-vh-80">
    <div class="container">
      <div class="row">
        <div class="col-xl-5 col-lg-3 col-md-7 d-flex flex-column mx-lg-0 mx-auto">
          <div class="card-header pb-0 text-center">
              <h4 style="padding-right: 60px;" class="font-weight-bolder ">Ooops, sorry... this page still in development!</h4>
          </div>
        </div>
        <div class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 end-0 text-center justify-content-center flex-column">
          <div class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center">
            <img src="{% static 'img/pattern-lines.svg' %}" alt="pattern-lines" class="position-absolute opacity-4 start-0">
            <div class="position-relative">
              <img class="max-width-500 w-100 position-relative z-index-2" src="{% static 'img/chat.png' %}">
            </div>
            <h4 class="mt-5 text-white font-weight-bolder">Manage leads</h4>
            <br>
            <p class="text-white">
                &copy; <a target="_blank" class="text-white">Lead generator app</a>
                <a class="text-white" target="_blank">- login and join us</a>.
              </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/interface/lead_generator.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<section>
  <div class="page-header min-vh-80 bg-gradient-primary">
    <div class="container">
      <div class="row">
        <div class="col-md-6 offset-md-3">
          <div class="card">
            <div class="card-header">
              <h4 class="card-title">Lead Generator</h4>
            </div>
            <div class="card-body">
              <form method="post" action="{% url 'interface:deploying' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <a href="{% url 'interface:deploying' %}" class="btn btn-primary">Generate Leads</a>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}